version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "miniforge3-latest"
  jobs:
    install:
      - which python
      - python -m pip install --no-deps --no-build-isolation .
      - python -c "import algait2de"
      - python -c "from algait2de import gait2de"
sphinx:
  configuration: docs/conf.py
formats: all
conda:
  environment: gait2d-dev.yml
