version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "miniforge3-latest"
  jobs:
    install:
      - which python
      - python -m pip install --no-deps --no-build-isolation .
sphinx:
  configuration: docs/conf.py
formats: all
conda:
  environment: gait2d-dev.yml
