/*
	autolevclean.c

	Program to extract clean C source code from C file generated by Autolev program gait2de.al

*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <time.h>

#define NDOF 9					// model has 9 DOF
#define STRLEN 100 				// source lines are never longer than 100 characters

int main() {

	FILE *fid1, *fid2;
	char line[STRLEN];
	int i, copying;
	char *ptr;

// FIRST WE CLEAN gait2de_al_raw.c

// open the file that came from Autolev
	if ((fid1 = fopen("gait2de_al_raw.c","r")) == NULL) {
		printf("Could not open gait2de_al_raw.c\n");
		exit(1);
	}

// write the clean C file
	if ((fid2 = fopen("gait2de_al.c","w")) == NULL) {
		printf("Could not write gait2de_al.c\n");
		exit(1);
	}

	// generate the function header
	fprintf(fid2,"// This file was generated by autolevclean.c and contains C code generated by Autolev\n\n");
	fprintf(fid2,"#include <math.h>\n");
	fprintf(fid2,"#include \"gait2de.h\"\n");
	fprintf(fid2,"void gait2d_al(param_struct* par, double q[NDOF], double qd[NDOF], double qdd[NDOF],\n");
	fprintf(fid2,"   double mom[NDOF], double GRF[6],\n");
	fprintf(fid2,"   double Stick[NSTICK*2]) {\n");;
	fprintf(fid2,"\n\tstatic double z[1198];\n");		// make sure there is enough room for all Zs
	fprintf(fid2,"\tconst double gravity = 9.81;\n");	// acceleration of gravity

	// generate C code to declare the temporary variables used in contact force model
	fprintf(fid2,"\tdouble dRHeel,	yRHeel,	FxRHeel,	FyRHeel,	xdotRHeel,	ydotRHeel;\n");
	fprintf(fid2,"\tdouble dLHeel,	yLHeel,	FxLHeel,	FyLHeel,	xdotLHeel,	ydotLHeel;\n");
	fprintf(fid2,"\tdouble dRToe,	yRToe,	FxRToe,		FyRToe,		xdotRToe,	ydotRToe;\n");
	fprintf(fid2,"\tdouble dLToe,	yLToe,	FxLToe,		FyLToe,		xdotLToe,	ydotLToe;\n");
	fprintf(fid2,"\tdouble dTrunkO,	yTrunkO,FxTrunkO,	FyTrunkO,	xdotTrunkO,	ydotTrunkO;\n");
	fprintf(fid2,"\tdouble dHip,	yHip,	FxHip,		FyHip,		xdotHip,	ydotHip;\n");
	fprintf(fid2,"\tdouble dRKnee,	yRKnee,	FxRKnee,	FyRKnee,	xdotRKnee,	ydotRKnee;\n");
	fprintf(fid2,"\tdouble dRAnkle,	yRAnkle,FxRAnkle,	FyRAnkle,	xdotRAnkle,	ydotRAnkle;\n");
	fprintf(fid2,"\tdouble dLKnee,	yLKnee,	FxLKnee,	FyLKnee,	xdotLKnee,	ydotLKnee;\n");
	fprintf(fid2,"\tdouble dLAnkle,	yLAnkle,FxLAnkle,	FyLAnkle,	xdotLAnkle,	ydotLAnkle;\n");

	// generate C code to declare the qpp variables and copy q and qd into scalar variables
	for (i=0; i<NDOF; i++) {
		fprintf(fid2,"\tdouble q%1dpp;\n", i+1);
		fprintf(fid2,"\tdouble q%1d = q[%1d];\n", i+1,i);
		fprintf(fid2,"\tdouble q%1dp = qd[%1d];\n", i+1,i);
	}

	// generate C code to copy joint moments into scalar variables
	for (i=0; i<NDOF; i++) {
		fprintf(fid2,"\tdouble mom%1d = mom[%1d];\n", i+1,i);
	}

	// copy the necessary parts of C code from fid1 to fid2
	copying = 0;
	while (feof(fid1) == 0) {
		fgets(line, STRLEN, fid1);
		if (strcmp(line, "/* Evaluate constants */\n") == 0) 				// Z[] code starts here
			copying = 1;
		else if (strcmp(line, "/* Evaluate output quantities */\n") == 0)	// Z[] code ends here
			copying = 0;
		else if (strcmp(line, "/* Write output to screen and to output file(s) */\n") == 0)		// kinematics code starts here
			copying = 1;
		else if (strcmp(line, "  Encode[0] = 0.0;\n") == 0)	// and stop here
			copying = 0;
		else if (copying) {
			// convert par__ into par->
			ptr = strstr(line, "par__");
			while (ptr != NULL) {
				strncpy(ptr, "par->", 5);
				ptr = strstr(line, "par__");
			}
			fputs(line, fid2);
		}
	}

// close the input file
	fclose(fid1);

// close the output file
	fprintf(fid2,"}\n");
	fclose(fid2);

}			// END OF MAIN PROGRAM
